### ISSUE TITLE
model.BaseAccountFieldSet is package private

### ISSUE THREAD

**Issue by kralikba** [SiftScience/sift-java#10]
Was this a conscious design decision? If yes, why? 
This hinders me in writing nice code that is common for its descendants.

**Comment by lopatin** [comment]
Thanks for pointing this out @kralikba . Making that class public sounds reasonable to me, I'll get a PR out for that shortly.

**Comment by lopatin** [comment]
Fixed in v1.3.1. Thanks @kralikba! Published to maven central but it in my experience it may take up to a day for the latest version to be actually become available there. Closing. Let me know if there are any other issues.
