### ISSUE TITLE
Cannot configure client connect or read timeouts

### ISSUE THREAD

**Issue by tmwilder** [SiftScience/sift-java#16]
Skimmed sources and it looks like there is no way to configure timeout on client calls (even with shenanigans like injecting a client, since the request constructors are not public.)

This is a bit limiting and forces unpleasant workarounds on callers wishing for bounded behavior - it would be useful to expose this to callers one way or another.

**Comment by quanpod** [comment]
Thanks @tmwilder - acknowledging the request.   Do you have particular scenarios you're trying to enable or eliminate (e.g. backend hangs when Sift is not responding fast enough?)

**Comment by tmwilder** [comment]
@quanpod - that's pretty much exactly the scenario! The goal is to have all components in a set of load balanced services nest their timeouts to make 504s nearly impossible and be able to reason about SLAs and failure mode behavior. 

Right now the user has to rely on okhttp default timeout, which doesn't assure longer term stability of behavior in the event where that changes and load on Sift causes slow responses.

Much more comfortable to be able to explicitly set and have guarantees on how tiered calls will behave.

**Comment by tmwilder** [comment]
The user can always do something gross like wrap in async call and time that out, but much better to have at least timeout exposed to consumer ;).

**Comment by quanpod** [comment]
@tmwilder just providing an update here - I'm taking a look across our libraries to understand where else we might make improvements, but we're not tackling this work just yet.  Let me know if there's other stuff you'd like to see improved via email (quan@siftscience.com)

**Comment by ehrmann** [comment]
@tmwilder

> shenanigans like injecting a client

#38 adds a public constructor for doing just that.

**Comment by aniranjan-sift** [comment]
Closing this issue as it is older than 2019 as per the following ticket:
https://sift.atlassian.net/browse/API-5373
