### ISSUE TITLE
Typo in serialization

### ISSUE THREAD

**Issue by hrootsi** [SiftScience/sift-java#17]
https://github.com/SiftScience/sift-java/blob/5c1bee031ec4e7630813eb4bed3081fc8ed5c1c0/src/main/java/com/siftscience/model/ApplyDecisionFieldSet.java#L51

**Comment by quanpod** [comment]
Thanks @hrootsi for the catch - will get this on our backlog.

**Comment by nitin21** [comment]
Fixed in [v1.4.1](https://github.com/SiftScience/sift-java/releases/tag/v1.4.1).
