### ISSUE TITLE
Decision requests failing 

### ISSUE THREAD

**Issue by smoock** [SiftScience/sift-java#18]
Customer is experiencing issues with the Java lib when applying decisions. A small number of decision events are failing before making it into Sift. They are using the standard Java lib, and using ApplyDecisionFieldSet with its setters to build the request. 

About .24% of the calls over the past 8 days have failed.

This is a log of the errors they are experiencing on their end:

> com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ 
> at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) 
> at com.google.gson.Gson.fromJson(Gson.java:887) 
> at com.google.gson.Gson.fromJson(Gson.java:852) 
> at com.google.gson.Gson.fromJson(Gson.java:801) 
> at com.google.gson.Gson.fromJson(Gson.java:773) 
> at com.siftscience.model.DecisionLog.fromJson(DecisionLog.java:21) 
> at com.siftscience.ApplyDecisionResponse.populateBodyFromJson(ApplyDecisionResponse.java:17) 
> at com.siftscience.SiftResponse.<init>(SiftResponse.java:27) 
> at com.siftscience.ApplyDecisionResponse.<init>(ApplyDecisionResponse.java:12) 
> at com.siftscience.ApplyDecisionRequest.buildResponse(ApplyDecisionRequest.java:31) 
> at com.siftscience.ApplyDecisionRequest.buildResponse(ApplyDecisionRequest.java:8) 
> at com.siftscience.SiftRequest.send(SiftRequest.java:45)

Normally they send a "looks_bad_legacy" and "looks_bad_account_abuse" for each decision, but this is indicating that for the errors they saw, we didn't receive any request.

**Comment by ehrmann** [comment]
22fa6c85 should fix this issue, but I'll hold off on closing the issue until the fix is verified.
