### ISSUE TITLE
OkHTTP Compiler Issue with 3.4.0

### ISSUE THREAD

**Issue by Alien2150** [SiftScience/sift-java#56]
Hey, 

I have an issue with Sift API 3.4.0. It seems it's compiled with a wrong OKHttp Version and therefore might cause issues with okio. The stack trace looks like this: 

```
Exception in thread "-kinesis-consumer-1" java.lang.NoSuchMethodError: 'okio.ByteString okio.ByteString.encodeString(java.lang.String, java.nio.charset.Charset)'
	at okhttp3.Credentials.basic(Credentials.java:35)
	at okhttp3.Credentials.basic(Credentials.java:30)
	at com.siftscience.ApplyDecisionRequest.modifyRequestBuilder(ApplyDecisionRequest.java:44)
	at com.siftscience.SiftRequest.send(SiftRequest.java:45)
	at com.jobtoday.sift.api.SiftApiImpl.send(SiftApiImpl.java:286)
```

I digged a bit more into this and found this on mvn:dependencyTree:

```
[INFO] +- com.siftscience:sift-java:jar:3.4.0:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.8.6:compile
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:3.14.8:compile
[INFO] |  \- com.squareup.okio:okio:jar:1.9.0:compile
```

But this is not the version specified in your gradle file: https://github.com/SiftScience/sift-java/blob/v3.4.0/build.gradle#L29

**Comment by Alien2150** [comment]
Can someone else check @quanpod maybe?

**Comment by quanpod** [comment]
Summoning @aaronTufts / @garylee1 who may know the right person (no longer at Sift, but hoping someone can help!)

**Comment by aaronTufts** [comment]
cc @jliu-sift

**Comment by aniranjan-sift** [comment]
`./gradlew distzip` seems to generate with different versions than `mvn dependency:tree` above

![Screen Shot 2021-06-14 at 10 01 11 AM](https://user-images.githubusercontent.com/75340113/121930741-8ed14580-ccf7-11eb-932f-036854bf78d3.png)

**Comment by aniranjan-sift** [comment]
Hi, we are closing this issue as `./gradlew distzip` is giving us the expected Okhttp version 0f `3.4.2` and we haven't updated our dependencies recently
