### ISSUE TITLE
LoginFieldSet doesn't have ability to set $user_email, which is necessary for Verification

### ISSUE THREAD

**Issue by atrout** [SiftScience/sift-java#58]
Hi,

We're attempting to use sift-java to send login events that might require verification. Unfortunately, the LoginFieldSet doesn't allow setting the `$user_email` field, which is necessary to trigger an email. I think if LoginFieldSet just extended BaseAccountFieldSet this would work.

Thanks!

**Comment by jliu-sift** [comment]
Hi @atrout! Thanks for the note. We'll get this prioritized.

**Comment by pjain-sift** [comment]
This is fixed and available in >= 3.4.1 releases.
