### ISSUE TITLE
Published POM has incorrect <packaging> info

### ISSUE THREAD

**Issue by kralikba** [SiftScience/sift-java#9]
In the POM published under https://search.maven.org/remotecontent?filepath=com/siftscience/sift-java/1.2/sift-java-1.2.pom, I believe that line 7 is incorrect. 
It is 
`<packaging>pom</packaging>`
while a JAR artifact is published. It should read
`<packaging>jar</packaging>`.

(This confuses my build, where the dependency resolution takes this info literally and does not look for a JAR.) Thanks.

**Comment by lopatin** [comment]
Thanks again for pointing out issues with the java client! It's fairly new so we're eager to hunt down publishing issues such as this one. I'll take a closer look at the pom/jar issue today.

**Comment by lopatin** [comment]
Fixed in v1.3.1. Please also see https://github.com/SiftScience/sift-java/issues/10#issuecomment-275458166
